name: kidspend3
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_sticky_header: "^0.3.4"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    # under assets/scenes
    - assets/arkhangelsk_1.png
    - assets/bolshoi_theatre_moscow.png
    - assets/chesme_church_st_petersburg.png
    - assets/church_in_uglich.png
    - assets/church_of_saviour_on_spilt_blood_1.png
    - assets/church_of_saviour_on_spilt_blood_2.png
    - assets/gagarin_monument_moscow.png
    - assets/komsomolskaya_moscow_metro.png
    - assets/lake_ladoga.png
    - assets/mayakovskaya_metro_moscow.png
    - assets/moscow_grocery_store.png
    - assets/moscow_immaculate_conception.png
    - assets/motherland_calls.png
    - assets/motherland_calls_mamayev_kurgan.png
    - assets/ostankino_tower_moscow.png
    - assets/peter_paul_fortress_spire.png
    - assets/peterhof_palace.png
    - assets/qolsharif_mosque_kazan_tatarstan.png
    - assets/resurrection_church_kremlin_rostov_veliky.png
    - assets/rostov_citadel.jpg
    - assets/scarlet_sails_st_petersburg.png
    - assets/sevastopol_memorial_1.jpg
    - assets/sevastopol_memorial_2.jpg
    - assets/singer_building_home_of_books_spb_1.png
    - assets/singer_building_home_of_books_spb_2.png
    - assets/smolny_convent_st_petersburg.png
    - assets/st_basils_cathedral_1.jpg
    - assets/st_basils_cathedral_2.jpg
    - assets/st_george_nykhas_uastyrdzhi_ossetia.png
    - assets/st_petersburg_rooftop_angels.png
    - assets/suzdal_church.png
    - assets/tall_trees.png
    - assets/transfiguration_church_kizhi_island_karelia.png
    - assets/trinity_church_bellingshausen_antarctica.png
    - assets/valaam_chapel.png
    - assets/valaam_icon.png
    - assets/valaam_monastery_1.png
    - assets/valaam_monastery_2.png
    - assets/vladivostok_trans_siberian_station.png
    # under assets/scenes-2
    - assets/buran.png
    - assets/control.png
    - assets/energia.png
    - assets/ice-station.png
    - assets/jurassic.png
    - assets/marche-vers-la-lumiere.png
    - assets/nostromo.png
    - assets/the-walk.png
    - assets/underground.png
    - assets/underground-moon.png
    # under assets/faces
    - assets/face1-trans.png
    - assets/face2-trans.png
    - assets/face3-trans.png
    # under assets/scenes-3
    - assets/buran-0.jpg
    - assets/buran-1.jpg
    - assets/buran-2.jpg
    - assets/buran-3.jpg
    - assets/buran-4.jpg
    - assets/buran-5.jpg

  fonts:
     - family: mermaid
       fonts:
         - asset: assets/Mermaid1001.ttf
     - family: bebas-neue
       fonts:
         - asset: assets/BebasNeue-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
